//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mail_Record_Application.Persistence
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MAIL
    {
        public int Id { get; set; }
        [Required(AllowEmptyStrings = true)]
        public string DIARY_NO { get; set; }
        [Required(AllowEmptyStrings = true)]
        public string SUBJECT { get; set; }
        [Required(AllowEmptyStrings = true)]
        public System.DateTime DATE_SENT { get; set; }
        [Required(AllowEmptyStrings = true)]
        public System.DateTime DATE_TODAY { get; set; }
        [Required(AllowEmptyStrings = true)]
        public string INITIATOR { get; set; }
        [Required(AllowEmptyStrings = true)]
        public string RECEIVED_FROM { get; set; }
        [Required(AllowEmptyStrings = true)]
        public string SENT_TO { get; set; }
        [Required(AllowEmptyStrings = true)]
        public string CC { get; set; }
        [Required(AllowEmptyStrings = true)]
        public string REMARKS { get; set; }
        [Required(AllowEmptyStrings = true)]
        public string MRDIARY_NO { get; set; }
    }
}
